name: Test
on:
  push:
  workflow_dispatch:
concurrency:
  group: test
  cancel-in-progress: true

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      #- uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DamianReeves/write-file-action@master
        with:
          path: flake.nix
          write-mode: overwrite
          contents: |
            {
              inputs = {
                nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
              };
              outputs = { self, nixpkgs }:
              let
                pkgs = import nixpkgs { system = "x86_64-linux"; };
                mesa = pkgs.mesa.overrideAttrs (oldAttrs: {
                  src = pkgs.fetchFromGitLab {
                    domain = "gitlab.freedesktop.org";
                    owner = "mesa";
                    repo = "mesa";
                    rev = "mesa-25.2.6";
                    hash = "sha256-erfvNR1Yor3k8gVVClyiBJsgyaOv7BMFd1NSgieTY5I=";
                  };
                });
              in
              {
                packages."x86_64-linux".default = mesa;
              };
            }
      - run: |
          nix build -L --print-out-paths --show-trace --keep-failed .#packages.x86_64-linux.default 2>&1 | tee log.txt
