name: Test
on:
  push:
  workflow_dispatch:
concurrency:
  group: test
  cancel-in-progress: true

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      #- uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DamianReeves/write-file-action@master
        with:
          path: flake.nix
          write-mode: overwrite
          contents: |
            {
              inputs = {
                nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
              };
              outputs = { self, nixpkgs }:
              let
                pkgs = import nixpkgs { system = "x86_64-linux"; };
                python3 = pkgs.python3.withPackages (python-pkgs: with python-pkgs; [
                  mako
                ]);
                venus-protocol = pkgs.fetchFromGitLab {
                  domain = "gitlab.freedesktop.org";
                  owner = "virgl";
                  repo = "venus-protocol";
                  rev = "9fa07f3cf7810df293abe0ff6a96032192f960d3";
                  hash = "sha256-g5Sbgr7I/2Nlt2h5yNWH4XM5sr6WPVgVfhFvgeBgZvU=";
                };
                mesa = pkgs.mesa.overrideAttrs (oldAttrs: {
                  src = pkgs.fetchFromGitLab {
                    domain = "gitlab.freedesktop.org";
                    owner = "mesa";
                    repo = "mesa";
                    rev = "766909b32110343c8a609188c0c76bd3b8df01af";
                    hash = "sha256-erfvNRaYor3k8gVVClyiBJsgyaOv7BMFd1NSgieTY5I=";
                    nativeBuildInputs = [ python3 ];
                    postFetch = ''
                      python3 ${venus-protocol}/vn_protocol.py --outdir $out/src/virtio/venus-protocol
                    '';
                  };
                });
              in
              {
                packages."x86_64-linux".default = mesa;
              };
            }
      - run: |
          nix build -L --print-out-paths --show-trace .#packages.x86_64-linux.default
